version: '2.2'
services:
  anon-check-relay:
    image: svforte/anon-dev
    restart: always
    volumes:
      - ./check-data/:/var/lib/anon
      - ./anonrc:/etc/anon/anonrc
  anon-check-service:
    image: anon-check
    depends_on:
      - anon-check-relay
    restart: always
    environment:
      INTERVAL_MINUTES: 1
      COLLECTOR_HOST: "http://host.docker.internal:9000"
    ports:
      - "8000:8000"
    volumes:
      - ./check-data/:/opt/check/data